# Generated by Django 5.2.4 on 2025-01-16 12:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Votre avis sur le produit', verbose_name='Commentaire')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Note entre 0.0 et 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='La note doit être au moins 0.0'), django.core.validators.MaxValueValidator(5.0, message='La note ne peut pas dépasser 5.0')], verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Contenu inapproprié'), ('spam', 'Spam'), ('offensive', 'Contenu offensant'), ('fake', 'Fausse information'), ('other', 'Autre raison')], max_length=20, verbose_name='Raison du signalement')),
                ('description', models.TextField(blank=True, verbose_name='Description du problème')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment', verbose_name='Commentaire signalé')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
            ],
            options={
                'verbose_name': 'Signalement de commentaire',
                'verbose_name_plural': 'Signalements de commentaires',
                'ordering': ['-created_at'],
                'unique_together': {('comment', 'reporter')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'rating'], name='comments_co_product_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='comments_co_user_id_123456_idx'),
        ),
    ]
