# Generated by Django 5.2.4 on 2025-08-16 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="comments_co_product_4f2c44_idx",
            old_name="comments_co_product_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comments_co_user_id_e44996_idx",
            old_name="comments_co_user_id_123456_idx",
        ),
    ]
