# Generated by Django 5.2.4 on 2025-08-09 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("CONSUMER", "Consommateur"), ("PRODUCER", "Producteur")],
                default="CONSUMER",
                help_text="Type de compte utilisateur",
                max_length=20,
                verbose_name="Type d'utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Nom de votre exploitation ou entreprise",
                        max_length=200,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Décrivez votre activité, vos méthodes de production, etc.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        help_text="Numéro SIRET de votre entreprise (optionnel pour MVP)",
                        max_length=14,
                        verbose_name="Numéro SIRET",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Adresse de votre exploitation",
                        verbose_name="Adresse complète",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Région française pour faciliter la recherche locale",
                        max_length=100,
                        verbose_name="Région",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le producteur a été vérifié par l'équipe GreenCart",
                        verbose_name="Producteur vérifié",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Producteur",
                "verbose_name_plural": "Producteurs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["region"], name="accounts_pr_region_330f2f_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="accounts_pr_is_veri_a96528_idx"
                    ),
                    models.Index(fields=["city"], name="accounts_pr_city_cbaee5_idx"),
                ],
            },
        ),
    ]
