# Generated by Django 5.2.4 on 2025-08-12 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_create_default_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Adresse de votre exploitation",
                verbose_name="Adresse complète",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="French phone number format: +33612345678 or 0612345678",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in French format. Example: +33612345678 or 0612345678",
                        regex="^(?:\\+33|0)[1-9]\\d{8}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
