# Generated by Django 5.2.4 on 2025-08-09 02:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_user_type_producer"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de commande généré automatiquement",
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de commande",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        help_text="Adresse complète de livraison",
                        verbose_name="Adresse de livraison",
                    ),
                ),
                (
                    "delivery_city",
                    models.CharField(max_length=100, verbose_name="Ville de livraison"),
                ),
                (
                    "delivery_postal_code",
                    models.CharField(
                        max_length=10, verbose_name="Code postal de livraison"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la commande en euros",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("SHIPPED", "Expédiée"),
                            ("DELIVERED", "Livrée"),
                        ],
                        default="PENDING",
                        help_text="Statut actuel de la commande",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de passage de la commande",
                        verbose_name="Date de commande",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de livraison souhaitée par le consommateur",
                        null=True,
                        verbose_name="Date de livraison souhaitée",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de confirmation de la commande",
                        null=True,
                        verbose_name="Confirmée le",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expédition de la commande",
                        null=True,
                        verbose_name="Expédiée le",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de livraison effective",
                        null=True,
                        verbose_name="Livrée le",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes ou instructions spéciales pour la commande",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "consumer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes laissées par le consommateur",
                        verbose_name="Notes du consommateur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Consommateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantité commandée",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de la commande",
                        max_digits=10,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix total pour cette ligne (quantité × prix unitaire)",
                        max_digits=10,
                        verbose_name="Prix total",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="accounts.producer",
                        verbose_name="Producteur",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commande",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("SHIPPED", "Expédiée"),
                            ("DELIVERED", "Livrée"),
                        ],
                        max_length=20,
                        verbose_name="Ancien statut",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("SHIPPED", "Expédiée"),
                            ("DELIVERED", "Livrée"),
                        ],
                        max_length=20,
                        verbose_name="Nouveau statut",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Raison ou commentaire sur le changement de statut",
                        verbose_name="Raison du changement",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Modifié le"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique des statuts",
                "verbose_name_plural": "Historiques des statuts",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["consumer", "-order_date"],
                name="orders_orde_consume_29e536_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_date"], name="orders_orde_order_d_d71205_idx"
            ),
        ),
    ]
