# Generated by Django 5.2.4 on 2025-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_data",
            field=models.TextField(
                blank=True,
                help_text="Photo principale encodée en base64",
                verbose_name="Photo du produit (Base64)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_format",
            field=models.CharField(
                blank=True,
                choices=[("JPEG", "JPEG"), ("PNG", "PNG"), ("WEBP", "WEBP")],
                help_text="Format de l'image principale",
                max_length=10,
                verbose_name="Format image",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_data",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Image encodée en base64 pour stockage en BDD",
                verbose_name="Données image (Base64)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_format",
            field=models.CharField(
                blank=True,
                choices=[("JPEG", "JPEG"), ("PNG", "PNG"), ("WEBP", "WEBP")],
                default="JPEG",
                help_text="Format de l'image",
                max_length=10,
                verbose_name="Format image",
            ),
        ),
    ]
