# Generated by Django 5.2.4 on 2025-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_image_remove_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                max_digits=3,
                null=True,
                verbose_name="Note du produit",
            ),
        ),
    ]
